name: Build and Test Java Spring Boot Application 
 
on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: 
      - '*'
 
jobs:
  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '11'
        postgresql db: mhfu-wiki
        postgresql user: mhfu-wiki
        postgresql password: mhfu-wiki

    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn clean verify
 
    - name: Test Report
      uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
          name: SpringBoot Report               # Name of the folder
          path: target/site/serenity/           # Path to test results

